### ISSUE TITLE
NAMESPACE token should be a fragment

### ISSUE THREAD

**Issue by pieterbos** [openEHR/adl-antlr#10]
The NAMESPACE token is ambiguous with ARCHETYPE_HRID, so sometimes a HRID matches as a NAMESPACE - result, parse error. 

Making namespace a fragment (it can only be used in one place, so that sounds right) solves this issue

**Comment by wolandscat** [comment]
This is now corrected.

**Comment by pieterbos** [comment]
Tested, now works.
