### ISSUE TITLE
UID does not parse dotted syntax

### ISSUE THREAD

**Issue by pieterbos** [openEHR/adl-antlr#13]
In the spec it says in the metadata section

| SYM_UID '=' ( DOTTED_NUMERIC | GUID )  // TODO: this won't match all Oids properly

In the grammar it says GUID only, so the dotted_numeric syntax does not, parse, for example 
openehr-TEST_PKG-WHOLE.child_with_oid.v1.0.0

```
archetype (adl_version=2.0.5; rm_release=1.0.2; uid=2.4.34.666.7.2)
    openehr-TEST_PKG-WHOLE.child_with_oid.v1.0.0
```

**Comment by wolandscat** [comment]
Good catch. Oids are a real nuisance. We don't want to allow them really, but this was done in response to a request from the Australian government. I think a better solution would be an 'oid=' parameter. I'll do some checking with others on this.

**Comment by wolandscat** [comment]
The grammar in its current version no longer matches OIDs anywhere; meta-data ids are now all GUIDs (UUIDs).

**Comment by pieterbos** [comment]
Sounds like a good solution. I'll remove the OID-files from archie.
